-- MySQL Script generated by MySQL Workbench
-- Wed Jan 29 21:16:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Table `gpxDb`.`Links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpxDb`.`Links` (
  `id` INT NOT NULL,
  `link` VARCHAR(254) NULL,
  PRIMARY KEY (`id`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`WPs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpxDb`.`WPs` (
  `id` INT NOT NULL,
  `lat` DECIMAL(11,9) NOT NULL,
  `lon` DECIMAL(12,9) NOT NULL,
  `ts` CHAR(20) NULL,
  `name` VARCHAR(254) NOT NULL,
  `sym` VARCHAR(62) NULL DEFAULT 'TRIANGLE',
  `type` VARCHAR(62) NULL DEFAULT 'WPT',
  PRIMARY KEY (`id`, `lat`, `lon`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`WPsAdd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpxDb`.`WPsAdd` (
  `id` INT NOT NULL,
  `cmt` VARCHAR(254) NULL,
  `desc` VARCHAR(254) NULL,
  `src` VARCHAR(254) NULL,
  `idLink` INT NULL,
  `extNs` VARCHAR(62) NULL,
  `extVal` LONGTEXT NULL,
  PRIMARY KEY (`id`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`RTEs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpxDb`.`RTEs` (
  `id` INT NOT NULL,
  `name` VARCHAR(254) NOT NULL,
  `number` INT NULL,
  `type` VARCHAR(64) NULL,
  PRIMARY KEY (`id`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`RTEsAdd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpxDb`.`RTEsAdd` (
  `id` INT NOT NULL,
  `cmt` VARCHAR(254) NULL,
  `desc` VARCHAR(254) NULL,
  `src` VARCHAR(254) NULL,
  `idLink` INT NULL,
  `extNs` VARCHAR(62) NULL,
  `extVal` VARCHAR(254) NULL,
  PRIMARY KEY (`id`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`RTEpts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpxDb`.`RTEpts` (
  `idRTE` INT NOT NULL,
  `id` INT NOT NULL,
  `lat` DECIMAL(11,9) NOT NULL,
  `lon` DECIMAL(12,9) NOT NULL,
  `name` VARCHAR(254) NULL,
  PRIMARY KEY (`idRTE`, `id`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`TRKs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpxDb`.`TRKs` (
  `id` INT NOT NULL,
  `name` VARCHAR(254) NOT NULL,
  `number` INT NULL,
  `type` VARCHAR(62) NULL,
  PRIMARY KEY (`id`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`TRKsAdd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpxDb`.`TRKsAdd` (
  `id` INT NOT NULL,
  `cmt` VARCHAR(254) NULL,
  `desc` VARCHAR(254) NULL,
  `src` VARCHAR(254) NULL,
  `extNs` VARCHAR(62) NULL,
  `extVal` VARCHAR(254) NULL,
  PRIMARY KEY (`id`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`TRKSegs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpxDb`.`TRKSegs` (
  `idTrk` INT NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`idTrk`, `id`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`TRKpts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpxDb`.`TRKpts` (
  `idTrkseg` INT NOT NULL,
  `id` INT NOT NULL,
  `lat` DECIMAL(11,9) NOT NULL,
  `lon` DECIMAL(12,9) NOT NULL,
  `ts` CHAR(20) NULL,
  PRIMARY KEY (`idTrkseg`, `id`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`RTEptsAdd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gpxDb`.`RTEptsAdd` (
  `id` INT NOT NULL,
  `extNs` VARCHAR(62) NULL,
  `extVal` VARCHAR(254) NULL,
  PRIMARY KEY (`id`))
;
