-- MySQL Script generated by MySQL Workbench
-- Wed Jan 29 21:16:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Table `gpxDb`.`Links`
-- -----------------------------------------------------
DROP TABLE IF EXISTS  gpxDb.Links;
create table gpxDb.Links (
    id integer primary key AUTOINCREMENT,
    link VARCHAR(254) NULL
)
;

-- -----------------------------------------------------
-- Table `gpxDb`.`WPs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS  gpxDb.WPs
;
CREATE TABLE `gpxDb`.`WPs` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `lat` DECIMAL(11,9) NOT NULL,
  `lon` DECIMAL(12,9) NOT NULL,
  `ts` CHAR(20) NULL,
  `name` VARCHAR(254) NOT NULL,
  `sym` VARCHAR(62) NULL DEFAULT 'TRIANGLE',
  `wpt` TEXT NULL,
  UNIQUE (`lat`, `lon`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`WPsAdd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gpxDb`.`WPsAdd`
;
CREATE TABLE `gpxDb`.`WPsAdd` (
  `id` INT NOT NULL,
  `cmt` VARCHAR(254) NULL,
  `desc` text NULL,
  `src` VARCHAR(254) NULL,
  `idLink` INT NULL,
  `extensions` TEXT NULL,
  UNIQUE (`id`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`RTEs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gpxDb`.`RTEs`
;
CREATE TABLE `gpxDb`.`RTEs` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(254) NOT NULL,
  `number` INT NULL,
  `type` VARCHAR(64) NULL,
  UNIQUE (`name`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`RTEsAdd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gpxDb`.`RTEsAdd`
;
CREATE TABLE `gpxDb`.`RTEsAdd` (
  `id` INT NOT NULL,
  `cmt` VARCHAR(254) NULL,
  `desc` VARCHAR(254) NULL,
  `src` VARCHAR(254) NULL,
  `idLink` INT NULL,
  `extNs` VARCHAR(62) NULL,
  `extVal` VARCHAR(254) NULL,
  UNIQUE (`id`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`RTEpts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gpxDb`.`RTEpts`
;
CREATE TABLE `gpxDb`.`RTEpts` (
  `idRTE` INT NOT NULL,
  `id` INT NOT NULL,
  `lat` DECIMAL(11,9) NOT NULL,
  `lon` DECIMAL(12,9) NOT NULL,
  `name` VARCHAR(254) NULL,
  UNIQUE (`idRTE`, `id`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`TRKs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gpxDb`.`TRKs`
;
CREATE TABLE `gpxDb`.`TRKs` (
  `id` INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` VARCHAR(254) NOT NULL,
  `number` INT NULL,
  `type` VARCHAR(62) NULL,
  UNIQUE (`name`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`TRKsAdd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gpxDb`.`TRKsAdd`
;
CREATE TABLE `gpxDb`.`TRKsAdd` (
  `id` INT NOT NULL,
  `cmt` VARCHAR(254) NULL,
  `desc` VARCHAR(254) NULL,
  `src` VARCHAR(254) NULL,
  `extNs` VARCHAR(62) NULL,
  `extVal` VARCHAR(254) NULL,
  UNIQUE (`id`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`TRKSegs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gpxDb`.`TRKSegs`
;
CREATE TABLE `gpxDb`.`TRKSegs` (
  `idTrk` INT NOT NULL,
  `id` INT NOT NULL,
  UNIQUE (`idTrk`, `id`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`TRKpts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gpxDb`.`TRKpts`
;
CREATE TABLE `gpxDb`.`TRKpts` (
  `idTrkseg` INT NOT NULL,
  `id` INT NOT NULL,
  `lat` DECIMAL(11,9) NOT NULL,
  `lon` DECIMAL(12,9) NOT NULL,
  `ts` CHAR(20) NULL,
  UNIQUE (`idTrkseg`, `id`))
;

-- -----------------------------------------------------
-- Table `gpxDb`.`RTEptsAdd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gpxDb`.`RTEptsAdd`
;
CREATE TABLE `gpxDb`.`RTEptsAdd` (
  `id` INT NOT NULL,
  `extNs` VARCHAR(62) NULL,
  `extVal` VARCHAR(254) NULL,
  UNIQUE (`id`))
;
